import tempfile
import unittest
from pathlib import Path

from agentic_pr.run_history import list_runs, get_run, get_last_run
from agentic_pr.run_record import RunRecord
from agentic_pr.config import AgentConfig


class RunHistoryTests(unittest.TestCase):
    def test_empty_run_directory(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            # Test with empty directory
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            records = list_runs(config, limit=10)
            self.assertEqual(len(records), 0)
            
            # Test with non-existent directory
            nonexistent = Path("/tmp/does-not-exist")
            config2 = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=nonexistent,
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            records = list_runs(config2, limit=10)
            self.assertEqual(len(records), 0)

    def test_invalid_json_skipped(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            # Create a run record file with invalid JSON
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            bad_record = config.run_record_dir / "run-123.json"
            bad_record.write_text("invalid json content")
            
            # Should not crash and should skip the invalid file
            records = list_runs(config, limit=10)
            self.assertEqual(len(records), 0)

    def test_list_runs_sorts_newest_first(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            # Create two run record files with different timestamps
            record1 = config.run_record_dir / "run-123.json"
            record1.write_text('{"run_id":"run-123","issue_number":1,"status":"pr_created","started_at":"2024-01-01T10:00:00"}')
            
            # Sleep to ensure different timestamps
            import time
            time.sleep(0.1)
            
            record2 = config.run_record_dir / "run-456.json"
            record2.write_text('{"run_id":"run-456","issue_number":2,"status":"failed","started_at":"2024-01-01T09:00:00"}')
            
            records = list_runs(config, limit=10)
            self.assertEqual(len(records), 2)
            # Should be sorted newest first (run-123 should come first)
            self.assertEqual(records[0].run_id, "run-123")
            self.assertEqual(records[1].run_id, "run-456")

    def test_get_run(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            record_file = config.run_record_dir / "run-123.json"
            record_file.write_text('{"run_id":"run-123","issue_number":1,"status":"pr_created","started_at":"2024-01-01T10:00:00"}')
            
            run = get_run(config, "run-123")
            self.assertIsNotNone(run)
            if run:
                self.assertEqual(run.run_id, "run-123")
                self.assertEqual(run.issue_number, 1)
                self.assertEqual(run.status, "pr_created")

    def test_get_run_not_found(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            run = get_run(config, "nonexistent")
            self.assertIsNone(run)

    def test_get_last_run(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            record1 = config.run_record_dir / "run-123.json"
            record1.write_text('{"run_id":"run-123","issue_number":1,"status":"pr_created","started_at":"2024-01-01T10:00:00"}')
            
            # Sleep to ensure different timestamps
            import time
            time.sleep(0.1)
            
            record2 = config.run_record_dir / "run-456.json"
            record2.write_text('{"run_id":"run-456","issue_number":2,"status":"failed","started_at":"2024-01-01T09:00:00"}')
            
            last_run = get_last_run(config)
            self.assertIsNotNone(last_run)
            if last_run:
                self.assertEqual(last_run.run_id, "run-123")  # Newest should be returned

    def test_get_last_run_empty(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            config = AgentConfig(
                repo_path=Path(tmp),
                owner_repo="test/repo",
                base_branch="main",
                model="ollama/qwen3-coder:30b",
                label_todo="agent-run",
                label_running="agent-running",
                label_done="agent-pr-created",
                label_failed="agent-failed",
                label_no_changes="agent-no-changes",
                label_blocked="agent-blocked",
                ollama_api_base="http://localhost:11434",
                aider_extra_args=(),
                log_dir=Path(tmp) / "logs",
                run_dir=Path(tmp) / "run",
                poll_interval_seconds=300,
                lock_file=Path(tmp) / "agent.lock",
                run_record_dir=Path(tmp) / "runs",
                agent_host_label="Mac Studio",
                comment_on_start=True,
                comment_on_success=True,
                comment_on_failure=True,
                comment_on_no_changes=True,
                aider_timeout_seconds=1800,
                max_changed_files=20,
                max_diff_lines=800,
                require_aiderignore=True,
                blocked_path_patterns=(".env",),
                test_cmd="",
                lint_cmd="",
                stale_lock_seconds=7200,
                enable_planner=True,
                planner_model="ollama/qwen3-coder:30b",
                repo_context_max_files=80,
                repo_context_max_bytes=120000,
                planner_timeout_seconds=900,
                comment_plan=True,
                enable_pr_followups=True,
                pr_followup_command_prefix="/agent",
                pr_followup_require_label=False,
                label_followup="agent-followup",
                label_followup_running="agent-followup-running",
                label_followup_done="agent-followup-done",
                label_followup_failed="agent-followup-failed",
                comment_state_dir=Path(tmp) / "comment-state",
                max_followup_comments_per_cycle=1,
                enable_ci_context=True,
                ci_command_aliases=("/agent fix-ci", "/agent fix checks", "/agent fix failing tests"),
                ci_log_max_lines=250,
                ci_log_max_bytes=40000,
                ci_include_successful_checks=False,
                ci_require_failed_checks=False,
                enable_repo_instructions=True,
                repo_instructions_dir=".agentic-pr",
                repo_instructions_max_bytes=40000,
                run_retention_days=30,
                log_retention_days=30,
                prompt_retention_days=30,
                comment_state_retention_days=90,
                max_log_preview_lines=80,
                service_label=None,
            )
            last_run = get_last_run(config)
            self.assertIsNone(last_run)